version: "3.9"
services:
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - o3
    ports:
      - "8000:8000"
  postgres:
      container_name: postgres_container
      image: postgres:13-alpine
      healthcheck:
        test: psql postgres --command "select 1" -U postgres
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - o3
      restart: unless-stopped

volumes:
  postgres:

networks:
  o3: