# Generated by Django 4.2.1 on 2023-05-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=20, choices=[(1, 'customer'), (2, 'provider')], default='customer'),
        ),
    ]
