# Generated by Django 4.2.1 on 2023-10-21 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AirlineCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_Date', models.DateField()),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('airline_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.airlinecode')),
            ],
        ),
        migrations.CreateModel(
            name='BookingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ECONOMY', 'ECONOMY'), ('PREMIUM_ECONOMY', 'PREMIUM_ECONOMY'), ('BUSINESS', 'BUSINESS'), ('FIRST', 'FIRST')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.address')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255)),
                ('personal_number', models.CharField(max_length=255)),
                ('issuing_country', models.CharField(max_length=50)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PASSPORT', 'PASSPORT'), ('NATIONAL_ID', 'NATIONAL_ID')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IATACode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD'), ('INFANT', 'INFANT')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MR', 'MR'), ('MS', 'MS'), ('MRS', 'MRS'), ('CHD', 'CHD'), ('INF', 'INF')], max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CANCELED', 'CANCELED'), ('REFUNDED', 'REFUNDED')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mame', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_mame', models.CharField(blank=True, max_length=255, null=True)),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_user_account', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.contact')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.document')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.gender')),
                ('passenger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.passengertype')),
                ('salutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.salutation')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField()),
                ('booked_segments', models.ManyToManyField(to='sky_scanner.bookedsegment')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.ticketnumber')),
                ('ticket_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.ticketstatus')),
                ('ticketing_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.airlinecode')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.traveller')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.documenttype'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.bookingreference')),
                ('tickets', models.ManyToManyField(to='sky_scanner.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookedsegment',
            name='booking_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.bookingclass'),
        ),
        migrations.AddField(
            model_name='bookedsegment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airports', to='sky_scanner.iatacode'),
        ),
        migrations.AddField(
            model_name='bookedsegment',
            name='flight_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.flightnumber'),
        ),
        migrations.AddField(
            model_name='bookedsegment',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airports', to='sky_scanner.iatacode'),
        ),
    ]
