# Generated by Django 4.2.1 on 2023-10-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatacode',
            name='airport_name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iatacode',
            name='city',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=6)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='sky_scanner.iatacode')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='sky_scanner.iatacode')),
            ],
        ),
    ]
