# Generated by Django 4.2.1 on 2023-10-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0007_referralcode_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
