# Generated by Django 4.2.1 on 2023-10-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0009_remove_bookedsegment_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_reference',
        ),
    ]
