# Generated by Django 4.2.1 on 2023-10-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0010_remove_booking_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.contact'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.gender'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='passenger_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.passengertype'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='salutation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.salutation'),
        ),
    ]
