# Generated by Django 4.2.1 on 2023-10-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0011_alter_traveller_contact_alter_traveller_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sky_scanner.document'),
        ),
    ]
