# Generated by Django 4.2.1 on 2023-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0012_alter_traveller_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
