# Generated by Django 4.2.1 on 2023-10-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0013_traveller_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_status',
        ),
    ]
