# Generated by Django 4.2.1 on 2023-10-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0014_remove_ticket_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booked_segments',
        ),
    ]
