# Generated by Django 4.2.1 on 2023-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0015_remove_ticket_booked_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='booked_segments',
            field=models.ManyToManyField(to='sky_scanner.bookedsegment'),
        ),
        migrations.AlterField(
            model_name='bookedsegment',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
