# Generated by Django 4.2.1 on 2023-10-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky_scanner', '0017_remove_bookedsegment_flight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedsegment',
            name='tax_percentage',
        ),
    ]
